source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'pg'
gem 'rails_admin'
gem 'rails_admin_nestable'
gem 'ckeditor'
gem 'devise'
gem 'cancan', '~> 1.6.10'
gem 'ancestry'
gem 'haml-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'gritter_notices'
gem 'kaminari'
gem 'compass-rails', github: "Compass/compass-rails"#, branch: "rails4-hack"
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'friendly_id', github: 'norman/friendly_id'
gem 'state_machine'
gem 'russian'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
  gem "capistrano", '~> 2.15.5'
  gem "rvm-capistrano", '~> 1.5.3'
end

gem 'unicorn'
